services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:8000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/app
    networks:
      - mynetwork

networks:
  mynetwork: